### ISSUE TITLE
Update array syntax to PHP7 

### ISSUE THREAD

**Issue by ghost** [Moment-Inc/craft-fbpixel#9]
Update array syntax in the Plugin file to use PHP7

**Comment by hahnzilla** [comment]
Dear Miguel,

Thanks for checking out the plugin! Would you mind providing either a pull request or some additional info on what should be updated?

**Comment by ghost** [comment]
Sorry about that, made the issue on my phone, must have botched it somehow. There is an older array syntax in the Plugin File that should be updated for PHP7.

Just made a pull request to fix this. Reference #10
